[goldmark]
  [goldmark.renderer]
    unsafe = true
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"

  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true

      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

[highlight]
  noClasses = false
  style = "github-dark"

[tableOfContents]
  startLevel = 2
  endLevel = 3
  ordered = false

