[[main]]
  name = "Music"
  pageRef = "tracks"
  weight = 10

[[main]]
  name = "Articles"
  pageRef = "articles"
  weight = 20

[[main]]
  name = "Genres"
  pageRef = "genres"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[main]]
  name = "YouTube"
  url = "https://www.youtube.com/channel/UC1-tLYf1HiKL5v0kHY90IvQ"
  weight = 50

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 10

[[footer]]
  name = "YouTube"
  url = "https://www.youtube.com/channel/UC1-tLYf1HiKL5v0kHY90IvQ"
  weight = 20
